### ISSUE TITLE
Error when using [item]

### ISSUE THREAD

**Issue by Catches** [Tanguygab/TAB-Additions#18] opened 2022-08-17 04:36 UTC
![image](https://user-images.githubusercontent.com/105005455/185035744-90345a13-7082-4b2e-8566-d7950c59d008.png)
Using [item] in-game doesn't work or print anything. Using version 1.6.5 on server version 1.19.2.

**Comment by Tanguygab** [comment] 2022-08-17 11:49
redownload https://github.com/Tanguygab/TAB-Additions/releases/tag/1.6.5 I've updated the jar with a fix

**Comment by Tanguygab** [comment] 2022-08-18 11:32
uh, send your chat.yml

**Comment by Tanguygab** [comment] 2022-08-18 15:37
alright, 1.19.2 (or 1.19.x, I'm not sure) broke something (thank you Mojang for that incredible Chat Reporting system)
I think the issue is from TAB, but we're not really sure why it does that, I'll let you know if we find anything

**Comment by Tanguygab** [comment] 2022-08-18 20:38
Fixed in the latest TAB build: https://github.com/NEZNAMY/TAB/actions/runs/2885253944

**Closed by Tanguygab** 2022-08-18 20:38 UTC
